apiVersion: v2
name: fraud-detection
description: Real-Time ML Fraud Detection System
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: redis
    version: "19.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
